#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 111 110 101 100 011 010 001 000

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

